Rails:
  Enabled: true

AllCops:
  TargetRubyVersion: 2.4.1

Style/Documentation:
  Enabled: false

Style/MixinUsage:
  Enabled: false

Metrics/LineLength:
  Max: 110

Style/ClassAndModuleChildren:
  Enabled: false
